version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test
      - deploy
jobs:
  build:
    executor: node
    steps:
      - run: npm install
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  deploy:
    executor: node
    steps:
      - run: npm run deploy
